export const blogPosts = [
  {
    id: 1,
    slug: "mastering-react-server-components-nextjs-14",
    title: "Mastering React Server Components in Next.js 14",
    excerpt: "Learn how to leverage React Server Components for better performance and SEO in your Next.js applications.",
    content: "React Server Components represent a fundamental shift in how we build React applications. Unlike traditional React components that render on the client, RSCs render on the server, significantly reducing bundle size and improving initial page load performance...",
    category: "frontend",
    readTime: "8 min read",
    date: "2024-01-15",
    author: "Mohibullah Mohim",
    image: "🚀",
    tags: ["React", "Next.js", "Performance", "RSC"],
    featured: true
  },
  {
    id: 2,
    slug: "scalable-backend-architecture-microservices",
    title: "Building Scalable Backend Architecture with Microservices",
    excerpt: "A comprehensive guide to designing and implementing microservices architecture for enterprise applications.",
    content: "Microservices architecture has become the go-to solution for building scalable and maintainable backend systems. By breaking down your application into smaller, independent services, you can achieve better separation of concerns, independent deployment, and improved fault isolation...",
    category: "backend",
    readTime: "12 min read",
    date: "2024-01-12",
    author: "Mohibullah Mohim",
    image: "🏗️",
    tags: ["Microservices", "Architecture", "Scalability", "Node.js"],
    featured: true
  },
  {
    id: 3,
    slug: "typescript-best-practices-production-applications",
    title: "TypeScript Best Practices for Production Applications",
    excerpt: "Essential TypeScript patterns and practices that will make your code more robust and maintainable.",
    content: "TypeScript has revolutionized how we write JavaScript, but using it effectively requires understanding best practices. From strict type checking to advanced generics, learn how to write TypeScript code that scales...",
    category: "frontend",
    readTime: "10 min read",
    date: "2024-01-10",
    author: "Mohibullah Mohim",
    image: "📘",
    tags: ["TypeScript", "Best Practices", "Development", "JavaScript"],
    featured: false
  },
  {
    id: 4,
    slug: "database-optimization-techniques-postgresql",
    title: "Advanced Database Optimization Techniques in PostgreSQL",
    excerpt: "Learn how to optimize your PostgreSQL database for maximum performance and scalability.",
    content: "Database performance is crucial for application scalability. PostgreSQL offers powerful optimization features including query planning, indexing strategies, and connection pooling that can dramatically improve your application's performance...",
    category: "database",
    readTime: "15 min read",
    date: "2024-01-08",
    author: "Mohibullah Mohim",
    image: "🐘",
    tags: ["PostgreSQL", "Database", "Optimization", "Performance"],
    featured: false
  },
  {
    id: 5,
    slug: "web-security-best-practices-2024",
    title: "Web Security Best Practices Every Developer Should Know in 2024",
    excerpt: "Essential security practices to protect your web applications from modern threats and vulnerabilities.",
    content: "Security is no longer an afterthought in web development. With increasing cyber threats, understanding and implementing security best practices is crucial. Learn about common vulnerabilities, authentication strategies, and security headers...",
    category: "security",
    readTime: "11 min read",
    date: "2024-01-05",
    author: "Mohibullah Mohim",
    image: "🛡️",
    tags: ["Security", "Web Development", "Authentication", "Best Practices"],
    featured: true
  },
  {
    id: 6,
    slug: "progressive-web-apps-modern-web",
    title: "Building Progressive Web Apps for the Modern Web",
    excerpt: "Create fast, reliable, and engaging web experiences with Progressive Web App technologies.",
    content: "PWAs bridge the gap between web and native mobile applications. Learn how to implement service workers, web app manifests, and offline functionality to create app-like experiences that work across all devices...",
    category: "mobile",
    readTime: "9 min read",
    date: "2024-01-03",
    author: "Mohibullah Mohim",
    image: "📱",
    tags: ["PWA", "Mobile", "Web Development", "Offline"],
    featured: false
  },
  {
    id: 7,
    slug: "api-design-rest-graphql-comparison",
    title: "REST vs GraphQL: Choosing the Right API Architecture",
    excerpt: "A comprehensive comparison between REST and GraphQL APIs with practical use cases and examples.",
    content: "Choosing between REST and GraphQL can significantly impact your application's performance and developer experience. Understand the trade-offs, use cases, and implementation details of both architectures...",
    category: "backend",
    readTime: "14 min read",
    date: "2024-01-01",
    author: "Mohibullah Mohim",
    image: "🔗",
    tags: ["API", "REST", "GraphQL", "Backend"],
    featured: false
  },
  {
    id: 8,
    slug: "devops-docker-kubernetes-guide",
    title: "Modern DevOps: Docker and Kubernetes Complete Guide",
    excerpt: "Master containerization and orchestration with Docker and Kubernetes for scalable deployments.",
    content: "Containerization has transformed how we deploy and manage applications. Learn Docker fundamentals, Kubernetes orchestration, and best practices for building robust DevOps pipelines...",
    category: "devops",
    readTime: "16 min read",
    date: "2023-12-28",
    author: "Mohibullah Mohim",
    image: "🐳",
    tags: ["Docker", "Kubernetes", "DevOps", "Containers"],
    featured: true
  }
];