export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description:
      "Full-stack e-commerce solution with React, Node.js, and MongoDB",
    image: "🛒",
    tags: ["React", "Node.js", "MongoDB", "Stripe"],
    liveLink: "#",
    githubLink: "#",
    featured: true,
  },
  {
    id: 2,
    title: "Task Management App",
    description: "Real-time collaborative task management application",
    image: "📋",
    tags: ["Next.js", "Socket.io", "PostgreSQL", "Tailwind"],
    liveLink: "#",
    githubLink: "#",
    featured: true,
  },
  {
    id: 3,
    title: "Weather Dashboard",
    description: "Beautiful weather application with advanced analytics",
    image: "🌤️",
    tags: ["React", "Chart.js", "API Integration", "PWA"],
    liveLink: "#",
    githubLink: "#",
    featured: false,
  },
];

export const projectsData = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description:
      "A full-stack e-commerce solution with real-time inventory, payment processing, and admin dashboard.",
    image: "/api/placeholder/600/400",
    technologies: ["Next.js", "TypeScript", "Node.js", "MongoDB", "Stripe"],
    liveLink: "#",
    githubLink: "#",
    featured: true,
    category: "web",
    status: "completed",
    demoUrl: "https://demo.example.com",
    githubUrl: "https://github.com/username/project",
    year: "2024",
    duration: "3 months",
    teamSize: "Solo",
    complexity: "Advanced",
  },
  {
    id: 2,
    title: "Task Management App",
    description:
      "Collaborative task management application with real-time updates, drag-drop functionality, and team collaboration features.",
    image: "/api/placeholder/600/400",
    technologies: ["React", "Firebase", "Tailwind CSS", "Framer Motion"],
    category: "web",
    status: "completed",
    demoUrl: "https://demo.example.com",
    githubUrl: "https://github.com/username/project",
    featured: true,
    year: "2024",
    duration: "2 months",
    teamSize: "Solo",
    complexity: "Intermediate",
  },
  {
    id: 3,
    title: "Weather Dashboard",
    description:
      "Real-time weather forecasting application with beautiful data visualizations and location-based services.",
    image: "/api/placeholder/600/400",
    technologies: ["Vue.js", "Chart.js", "OpenWeather API", "PWA"],
    category: "web",
    status: "completed",
    demoUrl: "https://demo.example.com",
    githubUrl: "https://github.com/username/project",
    featured: false,
    year: "2023",
    duration: "1 month",
    teamSize: "Solo",
    complexity: "Beginner",
  },
  {
    id: 4,
    title: "Mobile Fitness App",
    description:
      "Cross-platform fitness tracking application with workout plans, progress tracking, and social features.",
    image: "/api/placeholder/600/400",
    technologies: ["React Native", "Expo", "Firebase", "Redux"],
    category: "mobile",
    status: "in-progress",
    demoUrl: "https://demo.example.com",
    githubUrl: "https://github.com/username/project",
    featured: true,
    year: "2024",
    duration: "4 months",
    teamSize: "2 People",
    complexity: "Advanced",
  },
  {
    id: 5,
    title: "AI Content Generator",
    description:
      "AI-powered content generation tool with multiple templates, tone customization, and plagiarism checking.",
    image: "/api/placeholder/600/400",
    technologies: ["Python", "FastAPI", "React", "OpenAI API", "PostgreSQL"],
    category: "ai",
    status: "completed",
    demoUrl: "https://demo.example.com",
    githubUrl: "https://github.com/username/project",
    featured: true,
    year: "2024",
    duration: "5 months",
    teamSize: "3 People",
    complexity: "Expert",
  },
  {
    id: 6,
    title: "Social Media Analytics",
    description:
      "Comprehensive social media analytics dashboard with sentiment analysis and engagement metrics.",
    image: "/api/placeholder/600/400",
    technologies: ["Next.js", "D3.js", "Node.js", "MongoDB", "Redis"],
    category: "web",
    status: "completed",
    demoUrl: "https://demo.example.com",
    githubUrl: "https://github.com/username/project",
    featured: false,
    year: "2023",
    duration: "3 months",
    teamSize: "Solo",
    complexity: "Advanced",
  },
];
